### ISSUE TITLE
Publish battery level

### ISSUE THREAD

**Issue by zuckschwerdt** [ostrya/PresencePublisher#10]
Could the battery level be added to the messages?

The battery level could then be used to script some alerts about recharging or charging complete.

**Comment by ostrya** [comment]
I am not quite sure I understand your proposal. You want the presence message to contain the battery level of your phone each time a message is sent? What kind of scripting do you have in mind then?

In general, I would prefer not to add functionality that deviates too much from the initial aim (make your home automation aware that you are at home).

**Comment by zuckschwerdt** [comment]
Yes, pretty much. Or maybe just a battery low warning, whatever you see best suited.

Basically I keep forgetting to charge my devices, low power mode or shutdown then looks like the device went out of range. I'd like my HA to nag me about charging -- no reason anymore to keep checking on the devices then ;)
