### ISSUE TITLE
Subscription?

### ISSUE THREAD

**Issue by gerroon** [ostrya/PresencePublisher#14]
Hi,

I know this is a publisher but any plans to implement subcribing functionality too?

thanks

**Comment by ostrya** [comment]
No, sorry. The overall concept of the app is to connect to the MQTT broker only when publishing. And as there is no continuous connection, subscribing does not make sense. Maybe you can have a look at https://github.com/dc297/mqttclpro, this seems to offer subscription functionality.

**Comment by gerroon** [comment]
Thanks i will take a look at it.
