### ISSUE TITLE
Add username password

### ISSUE THREAD

**Issue by cnerone** [ostrya/PresencePublisher#2]
I agree,
this app appears simple but it's what I needed to publish my presence at home. 
I'm using homeassistant and mosquito server.
BTW I need username and password to access server (publishing or reading).
Any way to use them?

thank you very much

**Comment by ostrya** [comment]
Currently there is no support yet for username / password authentication. I'll see when I can manage to add it.

**Comment by pavel-gololobov** [comment]
See this PR: https://github.com/ostrya/PresencePublisher/pull/3

**Comment by cnerone** [comment]
thank you very much

On February 28, 2019 3:08:22 PM GMT+01:00, "Pavel V. Gololobov" <notifications@github.com> wrote:
>See this PR: https://github.com/ostrya/PresencePublisher/pull/3
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ostrya/PresencePublisher/issues/2#issuecomment-468285171

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
