### ISSUE TITLE
alarm clock

### ISSUE THREAD

**Issue by tomamplius** [ostrya/PresencePublisher#46]
Do you think that is possible to publish alarm clock? From Android clock?
Maybe from Android AlarmManager.
The goal is laucher action before wake up the morning.
Thanks for your reply.

**Comment by ostrya** [comment]
I don't quite understand. What would you like to do? Publish the next alarm clock time that you have set in the time app? Publish an event when your alarm clock rings?

**Comment by ostrya** [comment]
Sure, I will have a look.
