### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [ostrya/PresencePublisher#49]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 138 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on Presence Publisher (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve Presence Publisher's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by ostrya** [comment]
Sure, why not. Though I cannot guarantee fast responses, as I do this project only as a hobby and currently don't have much time to work on it.

Am 6. Mai 2022 05:58:50 MESZ schrieb Luis Guilherme ***@***.***>:
>I'm a PhD student interested in finding security vulnerabilities in open source projects.
>
>We found a total of 138 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on Presence Publisher (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).
>
>Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve Presence Publisher's security, and the quality of the reports of static analysis tools.
>
>(*) https://github.com/CROSSINGTUD/CryptoAnalysis
>

**Comment by ostrya** [comment]
Hi @misterAnderson90 are you still planning on doing an analysis here?

**Comment by ostrya** [comment]
I will close this issue due to inactivity.
