### ISSUE TITLE
No keyboard input in "Edit message" dialog text entry fields on Sony XA2

### ISSUE THREAD

**Issue by oniongarlic** [ostrya/PresencePublisher#53]
When trying to enter text into Name or Topic the touch keyboard won't show.

**Comment by ostrya** [comment]
Yes, you are right. I was aware of this already, but forgot to create a bug for it. The (un-released) 2.4.0-alpha version already contains a fix, but it also contains changes to the scheduling system that I would like to test a bit more before doing a proper release.

**Comment by ostrya** [comment]
Fix is now released.
