### ISSUE TITLE
Layout problem in the add message page 

### ISSUE THREAD

**Issue by piexpe** [ostrya/PresencePublisher#54]
**_Describe the bug_** 

**Dear developer**!  In the process of using, I found a bug in layout / display. As shown in the figure, **_in the Add message page_**, When the name input is too long, the input place of the name covers the place of the topic and vice versa. This may be an adaptation problem. I suspect it is because **_you don’t set the limit of the input._** App version is 2.4.1, my mobile phone is Pixel-2, screen resolution setting is 1080*1920, Android system is 12.0. The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.

<img width="132" alt="image" src="https://user-images.githubusercontent.com/67065017/184500793-49f45387-475c-4ec5-a361-b0fd8d6fa7e6.png">

**_Expected behavior_**
 
I hope that the page can be set to scroll, or can set the limit of the input, so that the problem can be solved.
 
_**Steps to reproduce this error**_
 
1.     Select Message tag
2.     Click Add Message button 
3.     Input a long senstence
4.     Will see this error 

_**Screenshots**_

<img width="132" alt="image" src="https://user-images.githubusercontent.com/67065017/184500793-49f45387-475c-4ec5-a361-b0fd8d6fa7e6.png">

_**Environment**_

- Version of Presence Publisher Android : 2.4.1,
- Device : Pixel-2,
- OS version : Android 12.0

**Comment by ostrya** [comment]
I guess I can introduce a limit to the input boxes, thanks for the suggestion.
