### ISSUE TITLE
Layout problem in the add message page

### ISSUE THREAD

**Issue by piexpe** [ostrya/PresencePublisher#55]
**_Describe the bug_** 

**Dear developer**!  In the process of using, I found a bug in layout / display. As shown in the figure, **_in the Add message page_**, When the input ( name or topic ) is “space” , the message will still be created. This will result in the input of one space and the input of many spaces not seeing any difference in the message. This may be an adaptation problem. I suspect it is because **_you didn't restrict the input of spaces._** App version is 2.4.1, my mobile phone is Pixel-2, screen resolution setting is 1080*1920, Android system is 12.0. The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.

<img width="351" alt="image-20220814201638964" src="https://user-images.githubusercontent.com/67065017/184536539-e2523efb-f078-4bd9-9fac-d1dd82796ef6.png">

**_Expected behavior_**

I hope that the page can be set to scroll, or can set the limit of the input, so that the problem can be solved.

_**Steps to reproduce this error**_

1.     Select Message tag
2.     Click Add Message button 
3.     Input some spaces
4.     Will see this error 

_**Screenshots**_

<img width="351" alt="image-20220814201638964" src="https://user-images.githubusercontent.com/67065017/184536533-723e68c5-4257-44eb-ab53-be4aac8b31ba.png">

_**Environment**_

- Version of Presence Publisher Android : 2.4.1,
- Device : Pixel-2,
- OS version : Android 12.0

**Comment by ostrya** [comment]
I guess I can trim the string before checking for emptyness. Thanks for the suggestion.
