### ISSUE TITLE
Add iBeacon detection and publishing

### ISSUE THREAD

**Issue by hubertbanas** [ostrya/PresencePublisher#6]
It would be great to integrate iBeacon detection and publishing as well. 

Similar to:
https://github.com/bjaanes/BeaconMqtt

**Comment by ostrya** [comment]
I agree that beacon detection would be nice. But as you mentioned, there is already BeaconMqtt for that. What would be the benefit in your opinion to add this functionality here? I'm asking because I currently do not own a beacon, so it is kind of hard to develop it with no way of testing.

**Comment by hubertbanas** [comment]
Presents detection using WiFi is just too slow which makes it unreliable. There are times user might be in WiFi range for some time but because their phone is in "deep sleep" state it will not even try to connect. See here for more details https://developer.android.com/training/monitoring-device-state/doze-standby

Connecting to Bluetooth Low Energy Beacons on the other hand is instantaneous. My idea would be to have inexpensive ESP32 modules act as iBeacon (see https://esphome.io/components/esp32_ble_beacon.html). Have multiple of them around the premises ex. one near the garage, the other close to the front door, etc. As soon as getting into their range the "PresencePublisher" would acts accordingly.

BeaconMQTT I mentioned is missing MQTT user authentication therefore not usable to many. It also have not seen updates in a long time.

**Comment by ostrya** [comment]
All right, I will see what I can do.
