### ISSUE TITLE
no beacons found on Samsung S22

### ISSUE THREAD

**Issue by robotsmiki** [ostrya/PresencePublisher#62]
on samsung S22 when I go "Add beacon" it does not find any, just the loading animation is shown. 
I have many beacons around me. All permissions are allowed.
Will test later on different phones if this a S22 issue.
App version 2.5.0 from F-Droid
![Screenshot_20230412_125014_Permission controller](https://user-images.githubusercontent.com/92318572/231436367-df18c89c-0c01-456f-8221-fc11ccc31a89.jpg)

**Comment by robotsmiki** [comment]
I've confirmed on a different version of android (9) in the same settings the beacon scan does work and shows a list of beacons around me. So it seems on android 13 there is a problem.

**Comment by robotsmiki** [comment]
seems like newer devices require new permissions that need to be added android.permission.BLUETOOTH_SCAN ans BLUETOOTH_CONNECT
https://developer.android.com/guide/topics/connectivity/bluetooth/permissions
Please add these permissions, I will gladly test if this works.

**Comment by ostrya** [comment]
Thanks for the hint, since all Bluetooth interaction is done in the library I use, I must have missed this new permission.
