### ISSUE TITLE
Android Phone stopped  sending online while connected to network

### ISSUE THREAD

**Issue by FireWizard52** [ostrya/PresencePublisher#69]
Hi,

First off all, I want to say thanks for this great app.
It has worked for several years with great satisfaction for me, telling me whether my phone was online or offline.
However, yesterday the app stopped with sending the correct network status. While online on my Wifi network it constantly sends offline.

I did already several things

- switching between Wifi and 4G
- rebooting the phone
- reinstalling and re configuring the app.

Nothing helps.
See the picture below

![Screenshot_presence-publisher-offline](https://github.com/user-attachments/assets/5c10cd42-2fce-43d0-9287-6bf79f746514)

Any suggestions? 

Regards

**Comment by ostrya** [comment]
Hi @FireWizard52, sorry to hear that. It sounds like the app does not detect the Wi-Fi name correctly anymore, which is probably related to the recent app update. Can you check what the "Detected conditions" log says?

**Comment by FireWizard52** [comment]
Hi, @ostrya,

Thank you very much for your quick response.

You asked,

> Can you check what the "Detected conditions" log says?

Unfortunately that screen is empty. So obviously nothing detected.

I did try to send the SSID, but that was not available. I showed NA.
That might match with your suggestion:

>  It sounds like the app does not detect the Wi-Fi name correctly anymore, which is probably related to the recent app update..

It would also be helpful for me to look at the Developer log if you could create an export and attach it here.

The developer log can be exported, but I can't find the location on my phone.
I have to sort that first, but don't know if I will succeed.

Regards

**Comment by FireWizard52** [comment]
Hi @ostrya 

Okay, I found it and was able to access it.
Here it is

[1725393509050.log](https://github.com/user-attachments/files/16855576/1725393509050.log)


Regards

**Comment by ostrya** [comment]
Thanks. Unfortunately, the log only confirms that there is something wrong with the network detection. I did rewrite that to allow directly sending events when connecting / disconnecting to configured networks. Can you tell me which Android OS version and which device type you are using?

**Comment by FireWizard52** [comment]
Hi, @ostrya,

> Can you tell me which Android OS version and which device type you are using?

I'm using a Motorola phone, type Moto G9 plus (XT2087-2)
Android version: 11

If you want more info, let me know.

Regards

**Comment by ostrya** [comment]
All right, so it looks like the detection method for wifi changes did not work as intended in Android 10 and 11. I just published version 2.6.2 (which will need some time to go through the Google Play review to be available) that should fix the issue. At least I could reproduce the behavior and verify the fix on an Android 11 emulator.

**Comment by FireWizard52** [comment]
Okay, @ostrya ,

Thank you for your quick fix.
I will wait until it is available in the Google Play store or F-Droid
and will report back, as soon I have updated from 2.6.1 to 2.6.2.

Regards

**Comment by FireWizard52** [comment]
Hello @ostrya,

Google has published the new release 2.6.2 in the Google Play store.
I updated the app to this version and everything works again as before.

Thank you very much for your quick response and solving this issue.

Best regards
